### ISSUE TITLE
Customize issue messages to describe intent

### ISSUE THREAD

**Issue by craigfurman** [ashanbrown/forbidigo#10]
When introducing forbidigo to a project or changing its patterns, it's often not clear to users who encounter its issues _why_ something has been forbidden. I've been working around this by leaving comments in `.golangci.yml` above each rule, but it'd be neat to see it in the editor, in the diagnostic itself, without having to navigate away or figure out where the tool is configured.

Example: instead of "forbidigo: use of `fmt.Errorf` forbidden by pattern `fmt\.Errorf`", we could customize that message to say "forbidigo: use of `fmt.Errorf` forbidden by pattern `fmt\.Errorf: please use pkg/errors in order to get proper stacktraces".

What do you think of this idea? I haven't given the command-line UX, or file config via golangci-lint a ton of thought, but I suppose breaking changes probably aren't ideal. Perhaps an accompanying golangci-lint change would be required to support an alternative, optional forbidigo schema:

current:

```yaml
    forbid:
      - ^print.*$
      - 'fmt\.Print.*'
```

optional extension:

```yaml
    forbid:
      # This array element is a map, and the value is a custom message
      - '^print.*$': 'a custom message'
      # this array element is a string, no custom message
      - 'fmt\.Print.*'
```

The command-line UX could get complicated. How much do we care about ergonomics here? If the recommended way to use this tool is via golangci-ling, we could even consider passing json snippets in:

```
forbidigo 'fmt\.Print.*' '{"pattern":  "^print.*$", "message": "a custom message"}'
```

Would you be interested in a PR for this?

**Comment by ashanbrown** [comment]
Including custom messages would be a great feature to add.  I also leave explanations in `.golangci.yml` but it would be great to have them surfaced by the linter.  I would love it if we could find a syntax that is a bit more human-readable than json would allow.

For golangci, we could support a new format that allows messages and pass these via an alternative optional interface.  For the CLI (which I'm sort of dubious anyone uses), things are a bit thicker.  We could support something like

`--extended <pattern> <message>`

although this would require doing more complex option parsing.

I am curious if there's some way to bake the message into the regex in a way that we can recognize that it is not a basic regex and extract it.  We could possibly leverage the fact that we can only forbid idenitfiers in order to create a syntax that allows us to embed a message.  Maybe something like:

```
![<your message here>]fmt.Printf.*
```

What do you think?

**Comment by craigfurman** [comment]
> I would love it if we could find a syntax that is a bit more human-readable than json would allow.

I'm inclined to agree actually. Even if this project is mostly used through golangci-lint config files, it'd be a shame to add json args to a CLI! I think something like your suggested syntax could work well. I'm happy to add something like that, but it might be a week or so before I can return to this issue with a PR.

> For golangci, we could support a new format that allows messages and pass these via an alternative optional interface

What do you think of the golangci syntax I proposed in the initial post?

**Comment by ashanbrown** [comment]
As per https://github.com/golangci/golangci-lint/blob/1fb67fe448da8a3fb525ecef28decceb23b42d7a/test/testdata/configs/forbidigo.yml#L2, the current golangci-lint syntax is:

```yaml
linters-settings:
  forbidigo:
    forbid:
      - fmt\.Print.*
```

I think your proposal is to have this be:

```yaml
linters-settings:
  forbidigo:
    forbid:
      - pattern: fmt\.Print.*
        message: No noise!
```

I'm trying to figure out how we can do this without breaking backwards config compatibility.  I don't know how much flexibility we have with the struct decoder in golangci lint.  It uses `mapstructure` which can be flexible but I doubt we'd be free to add hooks into the top-level decoding code just for these particular settings.  We might need to do something like:

```yaml
linters-settings:
  forbidigo:
    forbidWithMessage:
      - pattern: fmt\.Print.*
        message: No noise!
```

So again, the embedded comment syntax might be more desirable.  The embedded comment syntax might just be kicking the can though -- we might end up wanting more options in the future.  What do you think?

**Comment by craigfurman** [comment]
Ah I see what you mean. By using the extended but backwards compatible
string syntax in golangci, we don't even have to make any changes there.

Sounds like a plan to me! I'll see if I can get to a PR in the near future.
