### ISSUE TITLE
add spew.Dump to default forbidden patterns

### ISSUE THREAD

**Issue by jerome-laforge** [ashanbrown/forbidigo#2]
Please add [spew.Dump](https://pkg.go.dev/github.com/davecgh/go-spew/spew#Dump) as forbidden pattern.

From godoc overview, [spew](https://pkg.go.dev/github.com/davecgh/go-spew/spew#pkg-overview) is for debugging:
```
Package spew implements a deep pretty printer for Go data structures to aid in debugging.
```

**Comment by ashanbrown** [comment]
Forbidigo by itself doesn't have any exclusions.  I'll add `spew.Dump` to the list of suggestions on the READMe though. 
 Would you find it useful to have some common patterns available via some sort of command-line option (or as config option for golangci-lint?)?

**Comment by jerome-laforge** [comment]
Sorry, I missed that exclusions have not managed directly by Forbidigo.
I use Forbidigo via golangci-lint with no specific configuration for Fobidigo.

And I also missed that by default, the golangci-lint forbids `^fmt\.Print(|f|ln)$` (but I don't know where is it defined) as I can see it this prompt below
```
use of `fmt.Print` forbidden by pattern `^fmt\.Print(|f|ln)$` (forbidigo)
```

So maybe it will great to ask to golangci-lint to add spew.Dump as forbid pattern in it default config.

> Would you find it useful to have some common patterns available via some sort of command-line option (or as config option for golangci-lint)?

For golangci-lint, from my point of view it is clear enough with https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml#L396

**Comment by jerome-laforge** [comment]
So, I close this issue as it is more a problem with golintci-lint.

Thx for your support.

**Comment by jerome-laforge** [comment]
FYI, I just open this golangci/golangci-lint#1599

**Comment by jerome-laforge** [comment]
> Forbidigo by itself doesn't have any exclusions.

@ashanbrown, it seems that it is not actually the case with this [lines](https://github.com/ashanbrown/forbidigo/blob/633cfeeae6fdd209d2c84e64ed27db9c99c2770f/forbidigo/forbidigo.go#L44-L46). Is it possible to add `^spew\.Dump$` in this array? and it is quite similar to fmt.Print (that is already added in the default configuration).

/cc @ldez

**Comment by ldez** [comment]
maybe you can also add `^spew\.Print(|f|ln)$`

**Comment by ashanbrown** [comment]
Sorry @jerome-laforge, you are right.  It's been a while since I wrote this.  Looking at that list, it looks like I've chosen `fmt.Print*` as default.  I also never added `ginkgo\.F.*` as an option.  I think I had some reluctance to build a "dependency" of any sort on a third-party library such as `ginkgo` or `spew`.  With `fmt`, I feel this is a pretty safe guess about what library is being referenced, but we have no checking on what package an import came from, so I'm reluctant to make such assumptions for third-party libraries.
