### ISSUE TITLE
support import aliasing

### ISSUE THREAD

**Issue by pohly** [ashanbrown/forbidigo#20]
From the main page:
> Note that the linter has no knowledge of what packages were actually imported, so aliased imports will match these patterns.

So the  `^fmt\.Print.*$` pattern will not match in the following code, right?

```
import fmtstd "fmt"

func foo () {
   fmtstd.Print("forbidden")
}
```

Why does the linter have no knowledge about the actual package imports? I have added package lookup to some other linter (https://github.com/kubernetes-sigs/logtools/blob/6f17d4566e9a9bbd5751512a0b03fa0fac17e436/logcheck/pkg/logcheck.go#L264-L280), so this should be doable.

Would you be open to a PR that extends matching so that ``^fmt\.Print.*$` matches either the alias or the actual package (including its full path)?

**Comment by pohly** [comment]
If people start to get false positives, then they can extend their patterns to include the full module name.

**Comment by ashanbrown** [comment]
@pohly I'd be open to that.  I think I just never got around to implementing it.  This might also require updating golangci-lint to make sure we have import data available (see https://github.com/golangci/golangci-lint/blob/937e3d407bf4be560f95a93ae954f2636908f317/pkg/lint/lintersdb/manager.go#L415 where we set this).
