### ISSUE TITLE
Allow fmt\.Printf.* in examples

### ISSUE THREAD

**Issue by martin-sucha** [ashanbrown/forbidigo#3]
Example functions work by comparing the output printed, see https://blog.golang.org/examples. It would be useful to be able to ignore the Printf pattern within functions matching  `^Example.*` in files matching `.*_test.go$` as it's likely not there for debugging purposes.

**Comment by ashanbrown** [comment]
Thanks for this report @martin-sucha.  That's an interesting case.  It would require knowing the parent function of the code but I think that could be determined as we walk the AST.  For now, I suppose you might just ignore linter errors in `.*_test.go` (assuming you are using `golangci-lint`) but I agree this would be nice to fix.  I wonder if we'd want each pattern to indicate whether it is allowed in Examples.  There might also be a similar question about whether matches should be allowed in Tests or Benchmarks.  It might be useful to have a pattern syntax that could support that kind of customization.

**Comment by xiegeo** [comment]
I run into this problem too, here is my examples file:
https://github.com/xiegeo/modbusone/blob/359d1d49793c87e46b3e88f44413cf40dfe505a7/examples_test.go

The example is too long to put in a singal function so function name matching does not work in this case. For some reason it's not doing file based identification either. Is there a suggected solution for this problem?

**Comment by ashanbrown** [comment]
Hi @xiegeo, the logic is designed to allow fmt.Print (or whichever) inside of functions starting with `Example`, but I'm not sure how we'd identify that this is example code.  You've definitely pointed out a limitation.  Apart from determining that all invocations of a function were from examples (which seems very complicated), I'm not sure there's much to be done.  Assuming you're using golangci-lint, I think the best option is just to exclude the issue there.  If you can think of another approach, we could explore it.

**Comment by xiegeo** [comment]
@ashanbrown Not sure how it is done, but go doc is able to handle such example functions nicely: https://pkg.go.dev/github.com/xiegeo/modbusone#section-documentation

**Comment by martin-sucha** [comment]
See [Larger file examples in the blog post about examples](https://go.dev/blog/examples#:~:text=ExampleReverse_second()%0Afunc%20ExampleReverse_third()-,Larger%20examples,-Sometimes%20we%20need):

> A whole file example is a file that ends in _test.go and contains exactly one example function, no test or benchmark functions, and at least one other package-level declaration. When displaying such examples godoc will show the entire file.

**Comment by ashanbrown** [comment]
So I was just reviewing the code (it's been a while), and the code is supposed to ignore "whole file examples" at https://github.com/ashanbrown/forbidigo/blob/master/forbidigo/forbidigo.go#L138.  

However, the file mentioned above (
https://github.com/xiegeo/modbusone/blob/359d1d49793c87e46b3e88f44413cf40dfe505a7/examples_test.go) has more than one Example in it, so it technically is not a whole file example.
