### ISSUE TITLE
How to match sql.DB.Exec method calls?

### ISSUE THREAD

**Issue by fho** [ashanbrown/forbidigo#37]
Hello,

I want to use forbidigo to report usages of certain database/sql.DB methods.
As I understand the README.md, matching methods is possible.
I don't manage to do it though.
Am I doing something? Is it not supported? Is there maybe a bug preventing it?

Example `.go file:
```go
package main

import (
	"database/sql"
	"fmt"
)

func main() {
	var db *sql.DB
	db.Exec("SELECT * FROM users")
}
```

Goal: Forbidigo complains about the `db.Exec` call.

forbidigo calls that I tried and do not work:
```sh
forbidigo  -analyze_types '{p: "^sql\\.DB\\.Exec$"}' -- ./...
forbidigo  -analyze_types '{p: "sql\\.DB\\.Exec"}' -- ./...
forbidigo  -analyze_types '{p: "^sql\\.DB\\.Exec.*"}' -- ./...
```

Reporting the use of the DB type works though:
```sh
forbidigo  -analyze_types '{p: "^sql\\.DB"}' -- ./...
```

When specifying additonally the package import path, finding `sql.DB` also does not work anymore:
```sh
forbidigo  -analyze_types '{p: "^sql\\.DB", pkg: "^database/sql$" }' -- ./...
```

I'm using forbidigo version c506b285d7c219604e804a5578c14850b403f0ee.

**Comment by ashanbrown** [comment]
Thanks for this report.  It looks like we were not passing the `analyze_types` CLI option through to the analyzer.  Most people use the linter through golangci-lint, and I would recommend using that metalinter if possible.  Running each linter independently can be duplicate a lot of work.

**Comment by fho** [comment]
@ashanbrown thanks for the fix.

Yes, I started using it with golangci-lint but it did not work (because of yaml config indent errors, which I figured out later), so I checked if it works with the standalone version.
