### ISSUE TITLE
Allow forbidding keywords

### ISSUE THREAD

**Issue by utkuozdemir** [ashanbrown/forbidigo#47]
We would like to forbid usage of the `go` keyword in certain packages to prevent spawning "naked" goroutines (not via waitgroup/errgroup). This linter, as it works with identifiers, simply skips the keywords, making such rules impossible.

Would you consider adding support for keywords as well?

**Comment by ashanbrown** [comment]
That's an interesting use case.  I'd be inclined to write a separate new linter for that case or try to incorporate it into another metalinter (gocritic?).   One feature of this linter is that, unlike other linters, it requires detailed configuration (unlike, for example, the makezero linter I also maintain).  This configuration makes it more painful to incorporate into golangci-lint or to run on it's own.  I think your case is a case that can be clearly enumerated and so wouldn't require that level of flexibility.

I was looking to see if there is an existing linter for this and all I could find was an [unanswered SO question](https://stackoverflow.com/questions/76585359/golang-lint-rule-to-require-launching-a-goroutine-with-a-recover).

**Comment by utkuozdemir** [comment]
Thank you, I understand that it makes more sense as a separate linter. I might consider writing a new linter for this.
I already tried `ruleguard` with `gocritic` but it seemed like it also does not make what I need possible (unless I missed something).

Thanks for the linters, keep it up!

**Comment by alingse** [comment]
@ashanbrown while writing business code, we ran into similar issues where buggy code led to process crashes. We also expect this feature to forbid "go", a new linter is also expect.
