### ISSUE TITLE
Matching brackets

### ISSUE THREAD

**Issue by dguenms** [ashanbrown/forbidigo#49]
Hello,

we are using `slog` and would like to forbid the use of template strings to enforce structured logging. In other words, we would like to forbid regexes like:
```
^slog\.Info\(fmt\.Sprintf.*$
```
to match calls like:
```
slog.Info(fmt.Sprintf("some templated message string: %v", someValue))
```
Please ignore other log levels for simplicity. See here to illustrate that the regex should match: https://regex101.com/r/251BVr/2

However, it does not seem to be possible to match these using forbidigo. In fact, the regex
```
^slog\.Info.*$
```
does match (any `slog.Info` call in the codebase), while
```
^slog\.Info\(.*$
```
does not match any `slog.Info(` call in the codebase.

How am I supposed to match lines containing an opening bracket? I could not find an example of this use case.

**Comment by atom-andrew** [comment]
Hi @dguenms , sorry for the latest response.  forbidigo is really targeted at matching individual identifiers.  Anything involving parens exceeds what can be matched as an identifier.  I think that for your use case you'd want something that matches AST patterns.  I think such a tool could be really valuable and could hit a lot of cases that forbidigo can't.  I don't know of one out there, but I'm not up-to-date on go tooling and maybe someone has written it already.
